- name: using survey for filling this variables
  hosts: all
  tasks:
  - name: creating user {{ user_name }}
    ansible.builtin.user: 
     name: "{{ user_name }}"
     state: present
  - name: installing package {{ pkg_name }}
    ansible.builtin.dnf:
     name: "{{ pkg_name }}"
     state: latest
